# Generated by Django 3.0.5 on 2020-06-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMISSION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmstd', models.CharField(max_length=30)),
                ('regno', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('admission_date', models.DateField()),
                ('mobno', models.IntegerField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('discount', models.IntegerField()),
                ('fnm', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('os', models.CharField(max_length=30)),
                ('osc', models.CharField(max_length=30)),
                ('Previous_school', models.CharField(max_length=30)),
                ('Total_children', models.IntegerField(blank=True, null=True)),
                ('father_income', models.FloatField(blank=True, null=True)),
                ('mother_income', models.FloatField(blank=True, null=True)),
                ('mother_profession', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_education', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_mobno', models.IntegerField(blank=True, null=True)),
                ('mothername', models.CharField(blank=True, max_length=30, null=True)),
                ('father_mobno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employee', models.CharField(max_length=30)),
                ('joining_date', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('employee_type', models.CharField(max_length=60)),
                ('monthly_salary', models.FloatField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('father_name', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('bloodgroup', models.CharField(blank=True, choices=[('apos', 'A+'), ('aneg', 'A-'), ('bpos', 'B+'), ('bneg', 'B-'), ('opos', 'O+'), ('oneg', 'O-'), ('abpos', 'AB+'), ('abneg', 'AB-'), ('unspecified', '-')], default='-', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='INSTITUTECHANGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=50)),
                ('target_line', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='images/')),
                ('phone', models.IntegerField()),
                ('website', models.URLField(max_length=150)),
                ('address', models.CharField(max_length=80)),
                ('location', models.CharField(choices=[('us', 'United States'), ('uk', 'United Kingdom'), ('afg', 'Afghanistan'), ('albania', 'Albania'), ('Algeria', 'Algeria'), ('as', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('ab', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria')], max_length=10)),
                ('rules', models.TextField(default='aaaaavbbbbbbbvccccc', max_length=1000)),
                ('admission_fee', models.IntegerField(default='')),
                ('registration_fee', models.IntegerField()),
                ('art_material', models.CharField(max_length=30)),
                ('transport', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=100)),
                ('uniform', models.CharField(max_length=100)),
                ('fine', models.IntegerField()),
                ('others', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SUBJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectname', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
                ('classnm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eskoolyapp.CLASS')),
            ],
        ),
    ]
