# Generated by Django 3.0.5 on 2020-06-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMISSION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmstd', models.CharField(max_length=30)),
                ('regno', models.IntegerField()),
                ('image', models.FileField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('mobno', models.IntegerField()),
                ('fnm', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('os', models.CharField(max_length=30)),
                ('osc', models.CharField(max_length=30)),
                ('Previous_school', models.CharField(max_length=30)),
                ('Total_children', models.IntegerField()),
                ('father_income', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mother_income', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mother_profession', models.CharField(max_length=30)),
                ('mother_occupation', models.CharField(max_length=30)),
                ('mother_education', models.CharField(max_length=50)),
                ('mother_mobno', models.IntegerField()),
                ('mothername', models.CharField(max_length=30)),
                ('father_mobno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='INSTITUTECHANGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=50)),
                ('target_line', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='images/')),
                ('phone', models.IntegerField()),
                ('website', models.URLField(max_length=150)),
                ('address', models.CharField(max_length=80)),
                ('location', models.CharField(choices=[('us', 'United States'), ('uk', 'United Kingdom'), ('afg', 'Afghanistan'), ('albania', 'Albania'), ('Algeria', 'Algeria'), ('as', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('ab', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria')], max_length=10)),
                ('rules', models.TextField(default='aaaaavbbbbbbbvccccc', max_length=1000)),
                ('admission_fee', models.IntegerField()),
                ('registration_fee', models.IntegerField()),
                ('art_material', models.CharField(max_length=30)),
                ('transport', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=100)),
                ('uniform', models.CharField(max_length=100)),
                ('fine', models.IntegerField()),
                ('others', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SUBJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectname', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
                ('classnm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eskoolyapp.CLASS')),
            ],
        ),
    ]
