# Generated by Django 3.0.5 on 2020-07-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='name_of_class',
            new_name='classnm',
        ),
    ]
