# Generated by Django 3.0.5 on 2020-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutechange',
            name='admission_fee',
            field=models.IntegerField(default=''),
        ),
    ]
