# Generated by Django 3.0.5 on 2020-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0002_auto_20200621_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='discount',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='Total_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_mobno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_mobno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mothername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
