# Generated by Django 3.0.5 on 2020-07-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0002_auto_20200710_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
