# Generated by Django 3.0.5 on 2020-06-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0003_auto_20200622_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(default=6),
            preserve_default=False,
        ),
    ]
