# Generated by Django 3.0.5 on 2020-07-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0003_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_income',
            field=models.DateTimeField(),
        ),
    ]
