# Generated by Django 3.0.5 on 2020-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0004_admission_std_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('P', 'P'), ('L', 'L'), ('A', 'A')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
