# Generated by Django 3.0.5 on 2020-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0004_auto_20200702_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date_income',
            field=models.DateField(),
        ),
    ]
