# Generated by Django 3.0.5 on 2020-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0005_auto_20200702_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BALANCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=5000)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('net_balance', models.FloatField()),
            ],
        ),
    ]
