# Generated by Django 3.0.5 on 2020-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0005_admission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('P', 'P'), ('L', 'L'), ('A', 'A')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
