# Generated by Django 3.0.5 on 2020-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskoolyapp', '0006_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='expense_amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='income_amount',
            field=models.FloatField(default='0'),
        ),
    ]
